services:
  attack-flow:
    image: ghcr.io/jahaziellem/attack-flow:v4.0.0-space-frameworks
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_VERSION: v4.0.0-space-frameworks
    pull_policy: build
    ports:
      - 8080:80
    restart: always
