services:
  attack-flow:
    image: ghcr.io/jahaziellem/attack-flow:v3.2.1-sparta
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_VERSION: v3.2.1-sparta
    pull_policy: build
    ports:
      - 8080:80
    restart: always
