name: Deploy Vue.js app to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./src/attack_flow_builder/
        run: npm ci
      - name: Build
        working-directory: ./src/attack_flow_builder/
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: attack-flow-builder
          path: src/attack_flow_builder/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
