name: Docker Image

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Docker metadata
        id: af_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          labels: org.opencontainers.image.url=https://ctid.mitre.org/our-work/attack-flow/
      - name: Build Attack Flow Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.af_meta.outputs.tags }}
          labels: ${{ steps.af_meta.outputs.labels }}
